model:
  name: xib.models.relational_network.build_relational_network
  input_node_model:
    in_conv_shape: [256, 7, 7]
    in_linear_features: 3
    conv_channels: 256
    conv_layers: 2
    lin_features: 256
    lin_layers: 2
    fc_features: 256
    fc_layers: 2
  input_edge_model:
    in_linear_features: 10
    fc_features: 256
    fc_layers: 2
  edge_model:
    fc_features: 256
    fc_layers: 2
  output_global_model:
    fc_features: 256
    fc_layers: 2
    num_classes: 117

hparams:
  model/conv_layers--cvl: ${model.input_node_model.conv_layers}
  model/fc_layers--fcl: ${model.input_node_model.fc_layers}
  model/fc_features--fcf: ${model.input_node_model.fc_features}
