name: xib
comment: default config
tags:
  - ${dataset.name}

dataset:
  name: hico
  eager: yes
  folder: ./data
  trainval:
    split: .75
    name: ${dataset.name}_relationship_detection_train

dataloader:
  batch_size: 64
  num_workers: 1

optimizer:
  name: torch.optim.Adam
  weight_decay: 1.0e-05

scheduler: {}

losses:
  rank:
    weight: 0.
  bce:
    weight: 1.

checkpoint:
  keep: 2
  folder: ./runs

session:
  seed: ${random_seed:}
  device: cuda
  max_epochs: 35
  early_stopping:
    patience: 5

visual_relations:
  top_k_predicates: 5
  top_x_relations: 100
  activations: yes
  channel_mean: yes
  relevance_fn: relu_sum
  object_scores: yes

hparams:
  data--: ${dataset.name}
  loss/bce--lbce: ${losses.bce.weight}
  loss/rank--lrank: ${losses.rank.weight}
  opt/weight_decay--wd: ${optimizer.weight_decay}
  vr/topk--topk: ${visual_relations.top_k_predicates}
  vr/act--vra: ${visual_relations.activations}
  vr/chan_mean--vrcm: ${visual_relations.channel_mean}
  vr/rel_fn--vrrf: ${visual_relations.relevance_fn}
  vr/obj_score--vros: ${visual_relations.object_scores}
