name: xib
comment: default config
tags:
  - default

dataset:
  name: xib.datasets.HicoDet
  split: .75
  eager: yes
  trainval:
    folder: data/processed/hico_20160224_det/train
    input_mode: GT

# TODO probably this field is not needed
input: {}

dataloader:
  batch_size: 64
  num_workers: 1

optimizer:
  name: torch.optim.Adam
  weight_decay: 1.0e-05

scheduler: {}

losses:
  rank:
    weight: 0.
  bce:
    weight: 1.

checkpoint:
  every: 1
  folder: ~/experiments/xib/runs

session:
  device: cuda
  max_epochs: 35
  early_stopping:
    patience: 5

hparams:
  loss/bce--lbce: ${losses.bce.weight}
  loss/rank--lrank: ${losses.rank.weight}
  opt/weight_decay--wd: ${optimizer.weight_decay}
