name: xib
comment: default config
tags:
  - ${dataset.name}

dataset:
  name: hico
  eager: yes
  folder: ./data
  graph_type: human-object # fully_connected
  trainval:
    split: .75
    name: ${dataset.name}_relationship_detection_train

dataloader:
  batch_size: 64
  num_workers: 1

optimizer:
  name: torch.optim.Adam
  weight_decay: 1.0e-05

scheduler: {}

losses:
  rank:
    weight: 0.
  bce:
    weight: 1.

checkpoint:
  keep: 2
  folder: ./runs

session:
  seed: ${random_seed:}
  device: cuda
  max_epochs: 35
  early_stopping:
    patience: 5

hparams:
  data--: ${dataset.name}
  data/graph--dgt: ${dataset.graph_type}
  loss/bce--lbce: ${losses.bce.weight}
  loss/rank--lrank: ${losses.rank.weight}
  opt/weight_decay--wd: ${optimizer.weight_decay}
