name: xib
comment: default config
tags:
  - default

dataset:
  name: hico_det
  eager: yes
  image_dir: data/raw/hico_20160224_det/images/train2015
  trainval:
    folder: data/processed/hico_20160224_det/train
    split: .75

dataloader:
  batch_size: 64
  num_workers: 1

optimizer:
  name: torch.optim.Adam
  weight_decay: 1.0e-05

scheduler: {}

losses:
  rank:
    weight: 0.
  bce:
    weight: 1.

checkpoint:
  keep: 3
  folder: ~/experiments/xib/runs

session:
  seed: ${random_seed:}
  device: cuda
  max_epochs: 35
  early_stopping:
    patience: 5

visual_relations:
  top_k_predicates: 5
  top_x_relations: 100

hparams:
  loss/bce--lbce: ${losses.bce.weight}
  loss/rank--lrank: ${losses.rank.weight}
  opt/weight_decay--wd: ${optimizer.weight_decay}
  vr/topk--topk: ${visual_relations.top_k_predicates}
